name: Rust

on:
  pull_request:
    branches: [ main ]

jobs:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Prepare environment
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.DEVELOPMENT.txt ]; then pip install -r requirements.txt; fi
    - uses: pre-commit/action@v3.0.0